apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: server
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: server
    spec:
      containers:
      - command:
        - go
        - run
        - cmd/main.go
        image: superj80820/digimon-service
        name: server
        ports:
        - containerPort: 6000
        resources: {}
      restartPolicy: Always
status: {}
